"""crear tablas iniciales

Revision ID: 184d4e16fe55
Revises: 27a9628ed5c1
Create Date: 2026-02-16 15:44:11.049987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184d4e16fe55'
down_revision: Union[str, Sequence[str], None] = '27a9628ed5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('colores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colores_id'), 'colores', ['id'], unique=False)
    op.create_index(op.f('ix_colores_nombre'), 'colores', ['nombre'], unique=True)
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_id'), 'marcas', ['id'], unique=False)
    op.create_table('metodos_pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('recargo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metodos_pago_id'), 'metodos_pago', ['id'], unique=False)
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promociones_id'), 'promociones', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('talles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talles_id'), 'talles', ['id'], unique=False)
    op.create_index(op.f('ix_talles_nombre'), 'talles', ['nombre'], unique=True)
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compras_id'), 'compras', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['marcas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_table('cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cambios_id'), 'cambios', ['id'], unique=False)
    op.create_table('detalles_promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario_con_descuento', sa.Float(), nullable=False),
    sa.Column('id_promocion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_promocion'], ['promociones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_promocion_id'), 'detalles_promocion', ['id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto_sin_recargo', sa.Float(), nullable=False),
    sa.Column('monto_con_recargo', sa.Float(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_id'), 'pagos', ['id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_color', sa.Integer(), nullable=False),
    sa.Column('id_talle', sa.Integer(), nullable=False),
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_color'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_sucursal'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['id_talle'], ['talles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_table('detalles_compra',
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_compra_id'), 'detalles_compra', ['id'], unique=False)
    op.create_table('detalles_devolucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('id_cambio', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cambio'], ['cambios.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_devolucion_id'), 'detalles_devolucion', ['id'], unique=False)
    op.create_table('detalles_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_stock', sa.Integer(), nullable=False),
    sa.Column('id_promocion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_promocion'], ['promociones.id'], ),
    sa.ForeignKeyConstraint(['id_stock'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalles_venta_id'), 'detalles_venta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalles_venta_id'), table_name='detalles_venta')
    op.drop_table('detalles_venta')
    op.drop_index(op.f('ix_detalles_devolucion_id'), table_name='detalles_devolucion')
    op.drop_table('detalles_devolucion')
    op.drop_index(op.f('ix_detalles_compra_id'), table_name='detalles_compra')
    op.drop_table('detalles_compra')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_pagos_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_detalles_promocion_id'), table_name='detalles_promocion')
    op.drop_table('detalles_promocion')
    op.drop_index(op.f('ix_cambios_id'), table_name='cambios')
    op.drop_table('cambios')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_compras_id'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_talles_nombre'), table_name='talles')
    op.drop_index(op.f('ix_talles_id'), table_name='talles')
    op.drop_table('talles')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_promociones_id'), table_name='promociones')
    op.drop_table('promociones')
    op.drop_index(op.f('ix_metodos_pago_id'), table_name='metodos_pago')
    op.drop_table('metodos_pago')
    op.drop_index(op.f('ix_marcas_id'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_colores_nombre'), table_name='colores')
    op.drop_index(op.f('ix_colores_id'), table_name='colores')
    op.drop_table('colores')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
